### ISSUE TITLE
yarn packages not installed automatically

### ISSUE THREAD

**Issue by hexcowboy** [qiuxiang/coc-sol#1]
First of all, thanks for the repo. Take all my stars.

I just installed with `CocInstall coc-solidity` and had to manually go to my coc installation folder to install the node dependencies. Simply `cd /Users/hex/.config/coc/extensions/node_modules/coc-solidity && yarn`. Maybe there is a way to do this automatically when the package is installed from CoC?

**Comment by qiuxiang** [comment]
I will fix it in next release. Now I am rewriting a solidity lsp to provide more features, such as hover documentation.

**Comment by qiuxiang** [comment]
New version released with new language server. And this issue should be resolved.
