### ISSUE TITLE
How to config coc-settings.json

### ISSUE THREAD

**Issue by MonadeInFlask** [qiuxiang/coc-sol#11]
The code diagnostics works very show. I don't know where the problem is.

**Comment by qiuxiang** [comment]
cpu usage?

**Comment by MonadeInFlask** [comment]
> cpu usage?

好象不是cpu使用率问题，我就是敲了: CocInstall coc-solidity , 没配置coc-settings.json就直接使用了，但是在敲出一个错误代码后，要再多敲几行，它才反应出那个错误，修正后也是要多敲几行那个错误提示才消失，coc.nvim 和 neo的lsp都试着配过了，都是这样，有没有额外设置?

**Comment by qiuxiang** [comment]
没有额外配置，只要安装好官方的 solc

**Comment by qiuxiang** [comment]
能录个屏吗，还有 solc --version 看看

**Comment by MonadeInFlask** [comment]
> 能录个屏吗，还有 solc --version 看看

不知道怎么录， solc, the solidity compiler commandline interface
Version: 0.8.15+commit.e14f2714.Linux.g++

**Comment by qiuxiang** [comment]
确实有问题，我看看

**Comment by qiuxiang** [comment]
有 bug，我修一下

**Comment by MonadeInFlask** [comment]
> 有 bug，我修一下

辛苦了，是高版本的solc有bug吗

**Comment by qiuxiang** [comment]
不是，是项目的 bug

**Comment by MonadeInFlask** [comment]
最新补丁有修复吗

**Comment by qiuxiang** [comment]
close 的时候就已经修复了

**Comment by MonadeInFlask** [comment]
> 

谢谢，我试试。
