### ISSUE TITLE
Allow remapping for outside project folder

### ISSUE THREAD

**Issue by otavioschwanck** [qiuxiang/coc-sol#13]
i trying to remap for brownie using:

```json
  "solidity.remapping": {
    "@OpenZeppelin": "~/.brownie/packages/OpenZeppelin/openzeppelin-contracts@4.6.0/"
  },
```

and i solc tries to:
<img width="659" alt="image" src="https://user-images.githubusercontent.com/9551316/188279682-e12f4c8c-88ed-4551-97e8-84eecd94e11e.png">

**Comment by qiuxiang** [comment]
remapping not support `~/`, you should use absolute path.

See https://docs.soliditylang.org/en/latest/path-resolution.html#import-remapping

**Comment by otavioschwanck** [comment]
> remapping not support `~/`, you should use absolute path.
> 
> See https://docs.soliditylang.org/en/latest/path-resolution.html#import-remapping

only settings the remapping doesn't fixes, but this fixes:
```
  "solidity.remapping": {
    "@OpenZeppelin": "OpenZeppelin/openzeppelin-contracts@4.6.0"
  },
  "solidity.includePath": "/Users/otavio/.brownie/packages/",
```

Thanks for the answer
