### ISSUE TITLE
new upgrade breaks solidity (remappings)

### ISSUE THREAD

**Issue by TortoiseHive** [qiuxiang/coc-sol#3]
I was using:

  "solidity.remappings": [
    "@openzeppelin=./dependencies/openzeppelin-contracts-4.4.2",
    "@chainlink=./dependencies/chainlink-brownie-contracts@1.1.1"
  ],

Without that, the LSP dont start (using brownie here).

Can you add this back?

OS: Mac OS

![image](https://user-images.githubusercontent.com/100160179/159844583-5275ed6a-4f1f-4a06-bd83-42842867eb37.png)

The LSP is not working at all

**Comment by qiuxiang** [comment]
New lsp not support remappings. Only support `include_path` just like official compiler `solc`.  It looks like your dependencies directory are `dependencies` not `node_modules`. Why not just use npm to manage dependencies?

**Comment by TortoiseHive** [comment]
> New lsp not support remappings. Only support `include_path` just like official compiler `solc`. It looks like your dependencies directory are `dependencies` not `node_modules`. Why not just use npm to manage dependencies?

**Comment by TortoiseHive** [comment]
Its possible to do remappings with solc ?

**Comment by TortoiseHive** [comment]
> New lsp not support remappings. Only support `include_path` just like official compiler `solc`. It looks like your dependencies directory are `dependencies` not `node_modules`. Why not just use npm to manage dependencies?

brownie installs dependencies on home folder so we decided to put the dependencies in the project (to improve navigation on emacs (my coworker uses and dont have LSP yet))

Its possible to do the remappings in solc with include_path?  Would be awesome if could to use the @openzepellin in the file

https://docs.soliditylang.org/en/v0.8.11/path-resolution.html#import-remapping

**Comment by qiuxiang** [comment]
Ok, if solc supports remapping, I should also support it in this lsp.

**Comment by TortoiseHive** [comment]
New remaps are working perfectly, thanks!

EDIT:

This new server is awesome, this is how i configured:

  "solidity.remapping": {
      "@openzeppelin": "./dependencies/openzeppelin-contracts-4.4.2"
  },
