### ISSUE TITLE
Some limitations of new LS

### ISSUE THREAD

**Issue by TortoiseHive** [qiuxiang/coc-sol#4]
This new LS (solc) is good, but have some limitations:

new:
![image](https://user-images.githubusercontent.com/100160179/159956186-083f2977-8a1e-450d-b47e-0c39c343042a.png)

old:
![image](https://user-images.githubusercontent.com/100160179/159956658-5339596d-d92d-4918-a91e-2069c5e12c66.png)

It worth to keep this new LS?

**Comment by qiuxiang** [comment]
What is the declaration of juniorToken?

**Comment by TortoiseHive** [comment]
> What is the declaration of juniorToken?

JuniorToken public juniorToken;

JuniorToken is a ERC20 contract.

// SPDX-License-Identifier: MIT

pragma solidity >=0.8.7 <0.9.0;
```solidity

import "@openzeppelin/contracts/token/ERC20/ERC20.sol";

contract JuniorToken is ERC20 {
    constructor (string memory _name, string memory _symbol, uint256 _amount) ERC20(_name, _symbol) {
        _mint(msg.sender, _amount);
    }
}
```
Inside JuniorToken i can use the LSP
![image](https://user-images.githubusercontent.com/100160179/160039674-6c24fb09-02be-485c-a404-3f16264f9d89.png)

**Comment by qiuxiang** [comment]
I got it. That's what I say the LS has no tolerance.

You need type `juniorToken;` first (to make syntax correct ), then type `.` after `juniorToken`. Just like:

<img width=600 src=https://user-images.githubusercontent.com/1709072/160038734-ab6d7739-15d2-4833-9fc9-5d8ff2ab734c.png>

I have to say this is a bit inconvenient. But I still decided to develop new lsp. Because official compiler is more reliable.

**Comment by qiuxiang** [comment]
This problem can resolve with error recovery. Although it is not easy to implement.

**Comment by TortoiseHive** [comment]
> I got it. That's what I say the LS has no tolerance.
> 
> You need type `juniorToken;` first (to make syntax correct ), then type `.` after `juniorToken`. Just like:
> 
> <img alt="" width="600" src="https://user-images.githubusercontent.com/1709072/160038734-ab6d7739-15d2-4833-9fc9-5d8ff2ab734c.png">
> 
> I have to say this is a bit inconvenient. But I still decided to develop new lsp. Because official compiler is more reliable.

My JuniorToken already is ERC20, it have the ERC20 methods:

```
contract JuniorToken is ERC20 {
```

The LSP of coc-solidity@0.1.0 could detect the methods.

Just to be clear:

I have two files:

Lending and JuniorToken.

Lending have:
```
        juniorToken = new JuniorToken(string(abi.encodePacked(_tokenName, " jr")),
                                      string(abi.encodePacked("J", _tokenSymbol)), _juniorAmount);
```
the juniorToken already have a type, is a global variable of lending.

**Comment by qiuxiang** [comment]
u didn't get my point. I'm talking about syntax tolerance.

### Completions not working because syntax error (missing semicolon).
![Screenshot from 2022-03-25 12-37-09](https://user-images.githubusercontent.com/1709072/160055678-2a9a278a-e007-4d6b-932c-966f202524fa.png)

### Completions working
![Screenshot from 2022-03-25 12-42-48](https://user-images.githubusercontent.com/1709072/160055763-779fdcb8-3e2e-4fc9-becc-03b9a628fd4b.png)

**Comment by TortoiseHive** [comment]
![image](https://user-images.githubusercontent.com/100160179/160056868-c3bb8daa-f7ed-4271-861e-fe6a61cacc64.png)

![image](https://user-images.githubusercontent.com/100160179/160056893-64d0d237-aa79-4f7b-af97-42698d0b40ee.png)

![image](https://user-images.githubusercontent.com/100160179/160056999-dab49bdf-7b03-4d43-8335-69072b28587a.png)

(im calling inside the lending)

even with ; i dont get the transfer in LS.

With coc-solidity@0.1.0 in same place:

![image](https://user-images.githubusercontent.com/100160179/160057146-3b0d081e-b9ba-4e05-b751-249e42c6ceb6.png)

**Comment by qiuxiang** [comment]
can you give me a demo project to reproduce this issue?

**Comment by qiuxiang** [comment]
just some minimal codes to reproduce this issue.

**Comment by TortoiseHive** [comment]
> just some minimal codes to reproduce this issue.

Here:

https://github.com/TortoiseHive/test-coc-solidity

Use the contracts/Lending.sol to do the test.

Actual COC:
![image](https://user-images.githubusercontent.com/100160179/160058247-b71df1aa-faaa-48f3-9ffe-583845edafc5.png)


0.1.0 (appears 3 times, its strange):
![image](https://user-images.githubusercontent.com/100160179/160058322-c630cea1-8e27-4030-9b4f-ba36f72743d1.png)

**Comment by qiuxiang** [comment]
![Screenshot from 2022-03-25 13-10-57](https://user-images.githubusercontent.com/1709072/160058542-405f19e7-ee96-4359-9099-46e819dda72d.png)

**Comment by TortoiseHive** [comment]
> ![Screenshot from 2022-03-25 13-10-57](https://user-images.githubusercontent.com/1709072/160058542-405f19e7-ee96-4359-9099-46e819dda72d.png)

that awkward D:

Maybe something in my OS?

Can you test with my the config i use?

https://github.com/otavioschwanck/mood-nvim

My CocInfo:

```

## versions

vim version: NVIM v0.7.0-dev+1245-gf291a0339
node version: v14.18.1
coc.nvim version: 0.0.80-c9f7aa24 2022-03-24 23:11:36 +0800
coc.nvim directory: /Users/otavio/.local/share/nvim/site/pack/packer/start/coc.nvim
term: iTerm.app
platform: darwin

## Log of coc.nvim

2022-03-25T02:17:44.439 INFO (pid:57233) [services] - registered service "languageserver.dls"
2022-03-25T02:17:44.522 INFO (pid:57233) [plugin] - coc.nvim initialized with node: v14.18.1 after 152ms
2022-03-25T02:17:46.429 INFO (pid:57233) [attach] - receive notification: highlight []
2022-03-25T02:17:54.536 INFO (pid:57233) [services] - registered service "solidity"
2022-03-25T02:17:54.537 INFO (pid:57233) [services] - Solidity Language Server state change: stopped => starting
2022-03-25T02:17:54.575 INFO (pid:57233) [core-watchman] - watchman watching project: /Users/otavio/demo-for-coc-solidity
2022-03-25T02:17:54.814 INFO (pid:57233) [attach] - receive notification: highlight []
2022-03-25T02:17:56.866 INFO (pid:57233) [attach] - receive notification: highlight []
2022-03-25T02:17:57.695 INFO (pid:57233) [attach] - receive notification: highlight []
2022-03-25T02:17:58.527 INFO (pid:57233) [services] - Solidity Language Server state change: starting => running
2022-03-25T02:17:58.528 INFO (pid:57233) [services] - service solidity started
2022-03-25T02:18:00.183 INFO (pid:57233) [attach] - receive notification: showInfo []

```

Did you use the same remapping that i ?

EDIT:

![image](https://user-images.githubusercontent.com/100160179/160059346-3e64b223-d4b9-410d-ac23-730a554a61f6.png)

Is working now somehow (just in this demo project).  On my main project it doesn't work.  i will figure it out why tomorrow

**Comment by qiuxiang** [comment]
I think you still haven't got the point .

**Comment by qiuxiang** [comment]
The point is **tolerance**.

**Comment by TortoiseHive** [comment]
> I think you still haven't got the point .

i got, i need the ;

**Comment by TortoiseHive** [comment]
> I think you still haven't got the point .

I just pushed a new commit to the repository.

If some warning is present, this part stop working, probabily some error in LSP, not in coc.

EDIT:

Ignore, its not happening when i remove too.  Dont know how to reproduce =/

**Comment by qiuxiang** [comment]
https://user-images.githubusercontent.com/1709072/160060689-8be9a4e2-3fba-44e9-88bd-18cf7a771a55.mp4

**Comment by TortoiseHive** [comment]
Demo video:

https://www.dropbox.com/s/ykfdod6tntq4s6f/Grava%C3%A7%C3%A3o%20de%20Tela%202022-03-25%20%C3%A0s%2002.45.23.mov?dl=0

its very random, sometimes works, sometimes not (most of time not)

**Comment by qiuxiang** [comment]
member completion trigger by `.`, so u need delete `.` first, and then type `.` again.

**Comment by TortoiseHive** [comment]
Got it, now is working.

**Comment by TortoiseHive** [comment]
![image](https://user-images.githubusercontent.com/100160179/160115855-d41fb1b2-42fe-4dbe-90cb-82265f2efa63.png)

Working perfectly <3 Super thanks!
