### ISSUE TITLE
Add Snippets support for new LSP

### ISSUE THREAD

**Issue by TortoiseHive** [qiuxiang/coc-sol#5]
The new LSP inserts the functions with () even when have arguments.

**Comment by qiuxiang** [comment]
I would remove the insertion of () when I implement signature help.

**Comment by TortoiseHive** [comment]
Nice, thanks!

**Comment by qiuxiang** [comment]
https://user-images.githubusercontent.com/1709072/160064046-b89a221e-a401-4498-a565-7c786b908019.mp4

**Comment by qiuxiang** [comment]
And signature help, but only the basic implementation, only trigger by `(`

https://user-images.githubusercontent.com/1709072/160064158-583f5a9e-e295-4ae5-9e0b-2396ed07af12.mp4

**Comment by TortoiseHive** [comment]
Working perfectly, thanks!
