### ISSUE TITLE
How I configure compiler version?

### ISSUE THREAD

**Issue by chknlittle** [qiuxiang/coc-sol#6]
![image](https://user-images.githubusercontent.com/4612986/161023290-b957bf23-33a8-4b63-9877-d12d9d97a759.png)

Probably just a simple question but how can I resolve these errors?
Since there is a no tolerance policy I can't use the plugin if the compiler is not configured to the right version

**Comment by qiuxiang** [comment]
u can change to `pragma solidity ^0.8.10;`

**Comment by chknlittle** [comment]
can i do it without changing the solidity version of the contract i'm working on? dont want to cause problems with the people i'm working with

**Comment by qiuxiang** [comment]
I have plans to support specify solc version.  But I have no time to implement it in the near future.
coc-solidity@0.1.0 may work.

**Comment by qiuxiang** [comment]
done in https://github.com/qiuxiang/solidity-ls/commit/0ed97c3345bee8153f696e4b8e3dbe70bf22a007
