### ISSUE TITLE
Read remappings.txt like solidity-language-server

### ISSUE THREAD

**Issue by otavioschwanck** [qiuxiang/coc-sol#7]
The VSCODE lsp reads remappings from remappings.txt.  Would be nice if coc-solidity did that too

**Comment by qiuxiang** [comment]
u can use workspace level config, for example `.vim/coc-settings.json`:
```
{
  "solidity.remapping": {},
}
```

**Comment by qiuxiang** [comment]
this feature should be supported by new version.
