### ISSUE TITLE
definition and reference not found

### ISSUE THREAD

**Issue by nathanrs** [qiuxiang/coc-sol#8]
Hey, when I press gd or gr on any solidity file, I get `[coc.nvim] definition not found` or `[coc.nvim] reference not found`, even if the definition or reference is in the same file. Gd and gr works on my other language servers like rust. Any idea what the problem could be? Thanks

**Comment by qiuxiang** [comment]
`gd`, `gr` works only code syntax is correct

**Comment by nathanrs** [comment]
The code syntax is correct. I'm looking at code of large protocols that have already been deployed

**Comment by nathanrs** [comment]
I don't know, sometimes it works on files, other times it doesn't, I don't know the reason why, maybe it could be because my pragma was giving me an error. Anyways it's not an issue for what I'm working on now.
